### ISSUE TITLE
My Aviate Ideas

### ISSUE THREAD

**Issue by Norbiros** [MystPi/aviate#12]
1. Link tag: `{link <website> <text>}` (text is optional).
2. Tags Completion, when you start typing text with `{` it shows list with possible values, you can select value using arrows and click tab to select it (something like in [Minecraft](https://minecraft.fandom.com/wiki/Chat)).
3. Status per language - you can return different status, for different languages.
4. Better jokes - not just programming.
5. Status Icons - something like in github/discord.
6. Import status from ocular - if user's status isn't set, you can import from ocular.
7. When user mentions someone, it converts it to link (but this is client side code)
8. Words blacklist - system that blocks swearing in statuses.
9. Recently loved project (link to recently loved project)
Can you accept/reject my ideas?

**Comment by MystPi** [comment]
> 2\. Tags Completion, when you start typing text with `{` it shows list with possible values, you can select value using arrows and click tab to select it (something like in [Minecraft](https://minecraft.fandom.com/wiki/Chat)).

That sounds really cool but hard to implement.

> 3\. Status per language - you can return different status, for different languages.

Do you mean spoken language? If so, it would be hard to determine what language to use just from an API call.

> 4\. Better jokes - not just programming.

Feel free to make a PR with any if you want! I just copied random programming jokes from the internet. :P

> 5\. Status Icons - something like in github/discord.

I'm trying to limit Aviate to just statuses, but that's a good idea. Bear in mind that you could just set your status to something like `🤒 out sick` which is basically the same thing.

> 6\. Import status from ocular - if user's status isn't set, you can import from ocular.

Another great idea!

> 8\. Words blacklist - system that blocks swearing in statuses.

I don't like blacklists since it's very hard for them to be perfect. I think Aviate's mods will do a good enough job, and nobody has ever done it AFAIK so far.

**Comment by Norbiros** [comment]
> 
> > 3. Status per language - you can return different status, for different languages.
> 
> Do you mean spoken language? If so, it would be hard to determine what language to use just from an API call.
> 
We can get language using SA api (which returns language set in scratch settings).

> 
> > 5. Status Icons - something like in github/discord.
> 
> I'm trying to limit Aviate to just statuses, but that's a good idea. Bear in mind that you could just set your status to something like `🤒 out sick` which is basically the same thing.
> 
So I should work on this or not?

> I'm going to reject anything with client-side code, sorry. :(

It is client decision right? So If W_L accepts, can I create client side things in SA?
Maybe I can use `document.createElement` to add href element (xss is not possible)?

**Comment by MystPi** [comment]
> So I should work on this or not?

If you want to, of course!

> It is client decision right? So If W_L accepts, can I create client side things in SA?
> Maybe I can use `document.createElement` to add href element (xss is not possible)?

I'm still not going to implement those components though. I think it's best not to implement that in SA for now either.

**Comment by Norbiros** [comment]
> > It is client decision right? So If W_L accepts, can I create client side things in SA?
> > Maybe I can use `document.createElement` to add href element (xss is not possible)?
> 
> I'm still not going to implement those components though. I think it's best not to implement that in SA for now either.

But what with mentioning? No needs for new components?

**Comment by MystPi** [comment]
> > > It is client decision right? So If W_L accepts, can I create client side things in SA?
> > > Maybe I can use `document.createElement` to add href element (xss is not possible)?
> > 
> > 
> > I'm still not going to implement those components though. I think it's best not to implement that in SA for now either.
> 
> But what with mentioning? No needs for new components?

No, just components like `{link}`.

**Comment by MystPi** [comment]
I added the import from ocular button:
![image](https://user-images.githubusercontent.com/86574651/177207953-dc7105c0-df63-4ae9-a284-6faced2efe14.png)
You can try it out if you want at https://aviateapp.eu.org/dashboard.

**Comment by Norbiros** [comment]
Another idea, show name of user that fetches status. For example:
```Hey {visitor}!```

**Comment by MystPi** [comment]
> > Another idea, show name of user that fetches status. For example: `Hey {visitor}!`
> 
> Done in [811a0a0](https://github.com/MystPi/aviate/commit/811a0a0bb4feb0163163d9f72b1a96a7e3b8020e).

The 'visitors' feature was actually removed due to security reasons; I just forgot to post that here. 😅

**Comment by MystPi** [comment]
The problem with no. 9 is that SDB doesn't provide that information; otherwise, I would have already implemented it.

**Comment by Norbiros** [comment]
But what with scratch API?

**Comment by MystPi** [comment]
Extra API calls aren't really preferrable, but I'll look into it. :)

**Comment by MystPi** [comment]
Do you know what the API endpoint for recently loved is? All I could find is recently favorited.

**Comment by Norbiros** [comment]
You can get first element from loved projects.

**Comment by MystPi** [comment]
Yeah, but what endpoint would you use? I've looked at [this](https://en.scratch-wiki.info/wiki/Scratch_API) and can't seem to find anything.

**Comment by Adzboy** [comment]
> 4. Better jokes - not just programming.
Some good dad jokes would be nice

**Comment by MystPi** [comment]
> > 4. Better jokes - not just programming.
> 
> Some good dad jokes would be nice

Feel free to make a PR to add jokes to the list.
